import type { NetworkData } from "@/types/network"

/**
 * Load pre-computed network data from JSON files
 * These files should be generated by the data processing script
 */
export async function loadNetworkData(): Promise<NetworkData | null> {
  try {
    console.log("[v0] Starting to load network data...")

    // Load all data files in parallel
    const [graphResponse, narratorsResponse, hadithsResponse] = await Promise.all([
      fetch("/data/graph.json"),
      fetch("/data/narrators.json"),
      fetch("/data/hadiths.json"),
    ])

    console.log("[v0] Fetch responses:", {
      graph: graphResponse.ok,
      narrators: narratorsResponse.ok,
      hadiths: hadithsResponse.ok,
    })

    if (!graphResponse.ok || !narratorsResponse.ok || !hadithsResponse.ok) {
      console.error("[v0] Failed to load one or more data files")
      return null
    }

    const [graphData, narratorsData, hadithsData] = await Promise.all([
      graphResponse.json(),
      narratorsResponse.json(),
      hadithsResponse.json(),
    ])

    console.log("[v0] Loaded data:", {
      nodes: graphData.nodes?.length,
      edges: graphData.edges?.length,
      hadiths: hadithsData?.length,
    })

    // Transform the data to match our interface
    // Enrich graph nodes with full narrator details
    const nodes = graphData.nodes.map((node: any) => {
      const narratorDetails = narratorsData[node.id] || {}
      return {
        id: String(node.id),
        name: node.name || narratorDetails.name,
        grade: node.grade || narratorDetails.grade,
        degree: node.in_degree || narratorDetails.in_degree || 0,
        pagerank: node.pagerank || narratorDetails.pagerank || 0,
        betweenness: narratorDetails.betweenness || 0,
        in_degree: narratorDetails.in_degree || node.in_degree || 0,
        out_degree: narratorDetails.out_degree || 0,
        birth_date_place: narratorDetails.birth,
        death_date_place: narratorDetails.death,
        area_of_interest: narratorDetails.areas,
      }
    })

    const links = graphData.edges.map((edge: any) => ({
      source: String(edge.source),
      target: String(edge.target),
      weight: edge.weight || 1,
    }))

    const hadiths = hadithsData.map((hadith: any) => ({
      id: String(hadith.id),
      hadith_id: String(hadith.hadith_id),
      source: hadith.source,
      chapter: hadith.chapter,
      hadith_no: hadith.hadith_no,
      text_en: hadith.text_en || "",
      text_ar: hadith.text_ar || "",
      chain: hadith.chain.map(String), // Convert to strings to match node IDs
      narrator_names: hadith.narrator_names,
    }))

    console.log("[v0] Data transformation complete")

    return { nodes, links, hadiths }
  } catch (error) {
    console.error("[v0] Error loading network data:", error)
    return null
  }
}

/**
 * Load statistics data
 */
export async function loadStatistics() {
  try {
    const response = await fetch("/data/stats.json")
    if (!response.ok) return null
    return await response.json()
  } catch (error) {
    console.error("Error loading statistics:", error)
    return null
  }
}

/**
 * Map grade strings to standard format
 */
function mapGrade(grade: string): "sahih" | "hasan" | "daif" | "unknown" {
  if (!grade) return "unknown"
  const lower = grade.toLowerCase()

  if (lower.includes("thiqah") || lower.includes("trustworthy") || lower.includes("comp")) {
    return "sahih"
  }
  if (lower.includes("hasan")) {
    return "hasan"
  }
  if (lower.includes("daif") || lower.includes("weak")) {
    return "daif"
  }
  return "unknown"
}
