import type { NetworkData } from "@/types/network"

// Mock data for demonstration - replace with your actual data
export const mockNetworkData: NetworkData = {
  nodes: [
    { id: "1", name: "Abu Hurairah", nameArabic: "أبو هريرة", grade: "sahih", degree: 150, pagerank: 0.12 },
    { id: "2", name: "Ibn Abbas", nameArabic: "ابن عباس", grade: "sahih", degree: 120, pagerank: 0.1 },
    { id: "3", name: "Aisha", nameArabic: "عائشة", grade: "sahih", degree: 130, pagerank: 0.11 },
    { id: "4", name: "Umar ibn al-Khattab", nameArabic: "عمر بن الخطاب", grade: "sahih", degree: 100, pagerank: 0.09 },
    { id: "5", name: "Anas bin Malik", nameArabic: "أنس بن مالك", grade: "sahih", degree: 90, pagerank: 0.08 },
    { id: "6", name: "Al-Zuhri", nameArabic: "الزهري", grade: "sahih", degree: 80, pagerank: 0.07 },
    { id: "7", name: "Sufyan bin Uyaynah", nameArabic: "سفيان بن عيينة", grade: "sahih", degree: 70, pagerank: 0.06 },
    { id: "8", name: "Malik ibn Anas", nameArabic: "مالك بن أنس", grade: "sahih", degree: 85, pagerank: 0.075 },
    { id: "9", name: "Shu'bah", nameArabic: "شعبة", grade: "sahih", degree: 75, pagerank: 0.065 },
    { id: "10", name: "Ibn Umar", nameArabic: "ابن عمر", grade: "sahih", degree: 95, pagerank: 0.08 },
    {
      id: "11",
      name: "Jabir ibn Abdullah",
      nameArabic: "جابر بن عبد الله",
      grade: "sahih",
      degree: 60,
      pagerank: 0.05,
    },
    {
      id: "12",
      name: "Abdullah ibn Masud",
      nameArabic: "عبد الله بن مسعود",
      grade: "sahih",
      degree: 55,
      pagerank: 0.045,
    },
    {
      id: "13",
      name: "Salim ibn Abdullah",
      nameArabic: "سالم بن عبد الله",
      grade: "hasan",
      degree: 40,
      pagerank: 0.03,
    },
    { id: "14", name: "Nafi", nameArabic: "نافع", grade: "sahih", degree: 65, pagerank: 0.055 },
    { id: "15", name: "Urwah ibn Zubayr", nameArabic: "عروة بن الزبير", grade: "sahih", degree: 50, pagerank: 0.04 },
  ],
  links: [
    { source: "1", target: "6", weight: 25 },
    { source: "1", target: "7", weight: 20 },
    { source: "2", target: "6", weight: 22 },
    { source: "3", target: "15", weight: 18 },
    { source: "3", target: "6", weight: 15 },
    { source: "4", target: "10", weight: 30 },
    { source: "5", target: "6", weight: 28 },
    { source: "6", target: "8", weight: 35 },
    { source: "6", target: "9", weight: 32 },
    { source: "7", target: "8", weight: 20 },
    { source: "10", target: "13", weight: 25 },
    { source: "10", target: "14", weight: 28 },
    { source: "11", target: "6", weight: 15 },
    { source: "12", target: "9", weight: 18 },
    { source: "13", target: "14", weight: 12 },
    { source: "14", target: "8", weight: 22 },
    { source: "15", target: "6", weight: 20 },
  ],
  hadiths: [
    {
      id: "h1",
      text: "Actions are judged by intentions",
      textArabic: "إنما الأعمال بالنيات",
      collection: "Sahih Bukhari",
      book: "Book of Belief",
      number: "1",
      narrators: ["1", "6", "8"],
      path: ["Abu Hurairah", "Al-Zuhri", "Malik ibn Anas"],
    },
    {
      id: "h2",
      text: "The best of you are those who are best to their families",
      textArabic: "خيركم خيركم لأهله",
      collection: "Sunan at-Tirmidhi",
      book: "Book of Marriage",
      number: "3895",
      narrators: ["3", "15", "6"],
      path: ["Aisha", "Urwah ibn Zubayr", "Al-Zuhri"],
    },
    {
      id: "h3",
      text: "The strong person is not one who can wrestle others",
      textArabic: "ليس الشديد بالصرعة",
      collection: "Sahih Muslim",
      book: "Book of Virtue",
      number: "2609",
      narrators: ["1", "7", "8"],
      path: ["Abu Hurairah", "Sufyan bin Uyaynah", "Malik ibn Anas"],
    },
  ],
}
